# WARNING: This is an autogenerated plan. It may not behave as expected.
plan apache::install(
  TargetSpec $targets,
  String $src
) {
  $install_apache = run_task('package', $targets, "Install Apache using the packages task", {'action' => 'install', 'name' => 'nginx'})
  $start_apache = run_script('apache/start_apache.sh', $targets, "Starting Apache service")
  $upload_homepage = upload_file($src, '/usr/share/nginx/html/index.html', $targets, "Upload homepage")
}
